# The URL the site will be built for
base_url = "https://mikhailantoshkin.github.io/resume"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false
theme = "hermit_zola"
title = "Mikhail Antoshkin"

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = false

[extra]
home_subtitle = "Your frendly neighbourhood software engenier"

footer_copyright = ' &#183; <a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'

hermit_menu = [
    { link = "/posts", name = "Posts" },
    { link = "/resume", name = "Resume" }
]

hermit_social = [
    { name = "twitter", link = "https://twitter.com/mike_antoshkin" },
    { name = "github", link = "https://github.com/mikhailantoshkin" },
    { name = "linkedin", link = "https://www.linkedin.com/in/mikhail-antoshkin/" },
    { name = "email", link = "mike.antoshkin@gmail.com" }
]

[extra.highlightjs]
enable = true
clipboard = true
theme = "vs2015"


[extra.author]
name = "Mikhail Antoshkin"
email = "mike.antoshkin@gmail.com"
